sys:
    code: app
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    servlet:
      context-path: /kiilin-api

spring:
    # 环境 dev|test|prod
    profiles:
        active: @active@

    # 解决多个druid数据源放同一个tomcat下运行异常
    jmx:
      default-domain: kiilin-api
    # 关闭默认模板引擎
    thymeleaf:
      cache: false
      enabled: false
    # 热部署
    devtools:
      restart:
        enabled: true


# mybatis
mybatis:
  type-aliases-package: com.kiilin.**.dto.**
  mapper-locations: classpath*:mapper/**/*.xml

# mapper
# doc:  https://mapperhelper.github.io/docs/
#       https://gitee.com/free/Mapper/wikis/
mapper:
    mappers:
        - com.kiilin.common.tkmapper.AbstractMapper
    notEmpty: true
    before: true
    identity: MYSQL
    # 配置后会自动处理关键字 使用 {0} 替代原来的列名
    wrap-keyword: `{0}`
    # 配置为 true 后，delete 和 deleteByExample 都必须设置查询条件才能删除，否则会抛出异常。
    safe-delete: true
    safe-update: true

# pagehelper
# doc: https://github.com/pagehelper/Mybatis-PageHelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 改写逻辑删除
# 一下三个配置有其中一个未空就会调用到物理删除，请谨慎配置
delete:
  flag:
    # 逻辑删除的属性类型
    type: java.lang.Boolean
    # 逻辑删除的属性名（对应实体）
    name: delFlag
    # 逻辑删除的属性值（为该值时为逻辑删除）
    value: true


#logging
logging:
  config: classpath:logback-spring.xml

session:
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: true # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】